function [alpha1, alpha2] = los_angles(LOS, BC)
% Function that calculates the angles formed by the
% origin and the intersections points of the line of sight LOS
% with the boundary circle BC
%
% Input
% LOS		line of sight generated by createLine
% BC		boundary circle generated by createCircle

% Calculates the intersection between the LOS
% and the boundary circle
bci = intersectLineCircle (LOS, BC);
xi1 = bci(1,1);
yi1 = bci(1,2);
xi2 = bci(2,1);
yi2 = bci(2,2);

% Calculate the angle for the two intersections
if(yi1 >= 0)
    alpha1 = atan2(yi1, xi1);
  else
    alpha1 = 2*pi+atan2(yi1, xi1);
endif

if(yi2 >= 0)
    alpha2 = atan2(yi2, xi2);
  else
    alpha2 = 2*pi+atan2(yi2, xi2);
endif